// This file is auto-generated by @hey-api/openapi-ts

export const Body_ocr_pdf_ocr_postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_ocr_pdf_ocr_post'
} as const;

export const Body_submit_ocr_job_ocr_submit_postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_submit_ocr_job_ocr_submit_post'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const OCRJobStatusResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        progress: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['job_id', 'status', 'message'],
    title: 'OCRJobStatusResponse',
    description: 'Response for job status check'
} as const;

export const OCRJobSubmitResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        model: {
            type: 'string',
            title: 'Model'
        },
        dpi: {
            type: 'integer',
            title: 'Dpi'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        submitted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Submitted At'
        }
    },
    type: 'object',
    required: ['success', 'job_id', 'filename', 'total_pages', 'model', 'dpi', 'message', 'submitted_at'],
    title: 'OCRJobSubmitResponse',
    description: 'Response when submitting a new OCR job'
} as const;

export const OCRResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        total_pages: {
            type: 'integer',
            title: 'Total Pages'
        },
        dpi: {
            type: 'integer',
            title: 'Dpi'
        },
        model: {
            type: 'string',
            title: 'Model'
        },
        results: {
            additionalProperties: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'object',
            title: 'Results'
        },
        annotated_images: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Annotated Images',
            default: []
        },
        message: {
            type: 'string',
            title: 'Message',
            default: ''
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['success', 'filename', 'total_pages', 'dpi', 'model', 'results', 'created_at'],
    title: 'OCRResponse'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;
