// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import { ocrPdfSaveOcrPostResponseTransformer } from './transformers.gen';
import type { OcrPdfSaveOcrPostData, OcrPdfSaveOcrPostErrors, OcrPdfSaveOcrPostResponses, RootGetData, RootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 *
 * Health check endpoint
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/',
        ...options
    });
};

/**
 * Ocr Pdf Save
 *
 * Extract text and layout from a PDF using vLLM batch processing.
 * Returns the raw JSON response from vLLM.
 */
export const ocrPdfSaveOcrPost = <ThrowOnError extends boolean = false>(options: Options<OcrPdfSaveOcrPostData, ThrowOnError>) => {
    return (options.client ?? client).post<OcrPdfSaveOcrPostResponses, OcrPdfSaveOcrPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        responseTransformer: ocrPdfSaveOcrPostResponseTransformer,
        responseType: 'json',
        url: '/ocr',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};
