// This file is auto-generated by @hey-api/openapi-ts

import type { GetJobStatusOcrStatusJobIdGetResponse, OcrPdfOcrPostResponse, SubmitOcrJobOcrSubmitPostResponse } from './types.gen';

const ocrResponseSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const ocrPdfOcrPostResponseTransformer = async (data: any): Promise<OcrPdfOcrPostResponse> => {
    data = ocrResponseSchemaResponseTransformer(data);
    return data;
};

const ocrJobSubmitResponseSchemaResponseTransformer = (data: any) => {
    data.submitted_at = new Date(data.submitted_at);
    return data;
};

export const submitOcrJobOcrSubmitPostResponseTransformer = async (data: any): Promise<SubmitOcrJobOcrSubmitPostResponse> => {
    data = ocrJobSubmitResponseSchemaResponseTransformer(data);
    return data;
};

export const getJobStatusOcrStatusJobIdGetResponseTransformer = async (data: any): Promise<GetJobStatusOcrStatusJobIdGetResponse> => {
    data = ocrJobStatusResponseSchemaResponseTransformer(data);
    return data;
};
