// This file is auto-generated by @hey-api/openapi-ts

import type { OcrPdfSaveOcrPostResponse } from './types.gen';

export const ocrPdfSaveOcrPostResponseTransformer = async (data: any): Promise<OcrPdfSaveOcrPostResponse> => {
    return data;
};
