// This file is auto-generated by @hey-api/openapi-ts

import type { OcrPdfOcrPostResponse } from './types.gen';

const ocrResponseSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    return data;
};

export const ocrPdfOcrPostResponseTransformer = async (data: any): Promise<OcrPdfOcrPostResponse> => {
    data = ocrResponseSchemaResponseTransformer(data);
    return data;
};
