// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8003' | (string & {});
};

/**
 * Body_ocr_pdf_save_ocr_post
 */
export type BodyOcrPdfSaveOcrPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OCRResponse
 *
 * The main API response.
 */
export type OcrResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Filename
     */
    filename: string;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Dpi
     */
    dpi: number;
    /**
     * Results
     */
    results: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    /**
     * Message
     */
    message?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OcrPdfSaveOcrPostData = {
    body: BodyOcrPdfSaveOcrPost;
    path?: never;
    query?: {
        /**
         * Dpi
         */
        dpi?: number;
        /**
         * Output Folder
         */
        output_folder?: string | null;
    };
    url: '/ocr';
};

export type OcrPdfSaveOcrPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OcrPdfSaveOcrPostError = OcrPdfSaveOcrPostErrors[keyof OcrPdfSaveOcrPostErrors];

export type OcrPdfSaveOcrPostResponses = {
    /**
     * Successful Response
     */
    200: OcrResponse;
};

export type OcrPdfSaveOcrPostResponse = OcrPdfSaveOcrPostResponses[keyof OcrPdfSaveOcrPostResponses];
