// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8003' | (string & {});
};

/**
 * Body_ocr_pdf_ocr_post
 */
export type BodyOcrPdfOcrPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OCRResponse
 */
export type OcrResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Filename
     */
    filename: string;
    /**
     * Total Pages
     */
    total_pages: number;
    /**
     * Dpi
     */
    dpi: number;
    /**
     * Model
     */
    model: string;
    /**
     * Results
     */
    results: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    /**
     * Annotated Images
     */
    annotated_images?: Array<string>;
    /**
     * Message
     */
    message?: string;
    /**
     * Created At
     */
    created_at: Date;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAvailableModelsOcrModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ocr/models';
};

export type GetAvailableModelsOcrModelsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OcrPdfOcrPostData = {
    body: BodyOcrPdfOcrPost;
    path?: never;
    query?: {
        /**
         * Dpi
         */
        dpi?: number;
        /**
         * Model
         *
         * OCR model to use
         */
        model?: string;
        /**
         * Annotate
         */
        annotate?: boolean;
        /**
         * Output Folder
         */
        output_folder?: string | null;
    };
    url: '/ocr';
};

export type OcrPdfOcrPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OcrPdfOcrPostError = OcrPdfOcrPostErrors[keyof OcrPdfOcrPostErrors];

export type OcrPdfOcrPostResponses = {
    /**
     * Successful Response
     */
    200: OcrResponse;
};

export type OcrPdfOcrPostResponse = OcrPdfOcrPostResponses[keyof OcrPdfOcrPostResponses];
